language: haxe

os: linux
dist: trusty

haxe:
  - development
  - "3.4.4"

matrix:
  allow_failures:
    - haxe: development
    
script:
  - yes | haxelib install all
  - all.hxml
  - cd samples
  - yes | haxelib install all
  - all.hxml

notifications:
  email: false
